### ISSUE TITLE
we need data over time for temperature, not 12-month averages

### ISSUE THREAD

**Issue by savannarreid** [DanielRobertNicoud/GeoDataCovid19Dataset#1]
This is going to be a pandemic with a seasonal trend, from what we know so far. We need data over time for temperature, not 12-month averages. Are there smaller geographic areas for which we have both good COVID-19 surveillance and good data-over-time for temperature? For the U.S. we have regional climate centers: https://www.ncdc.noaa.gov/customer-support/partnerships/regional-climate-centers so I think we may need to focus on the 50 state regression for now, unless we can find something similar for the EU as well.

**Comment by DanielRobertNicoud** [comment]
https://www.ncdc.noaa.gov has daily data from all around the world, I'm working on extracting that. Afterwards we can reduce the scope as needed or split datasets (eg US, Europe, Asia). I've put a first part of the scrapper in the folder. Will update in the next few hours.
